### ISSUE TITLE
Getting log likelihood or log posterior from Turing?

### ISSUE THREAD

**Issue by luiarthur** [luiarthur/TuringBnpBenchmarks#7]
In Turing, is there a way to get something like `lp__` in STAN?

**Comment by trappmartin** [comment]
Is the `lp__` field in Stan the log posterior predictive probability?

**Comment by luiarthur** [comment]
`lp__` in STAN is a "scaled" log likelihood. STAN has some clever way of getting rid of proportionality constants, to save on some computation, hence you get a scaled log likelihood (more correctly, log of the scaled likelihood). If done correctly, you can save quite a bit of compute. One issue with this is you have to be careful when using it to compare models. You have to know what exactly what constants are removed in the process.

I would be content with a log likelihood.

**Comment by trappmartin** [comment]
I think you can use the `logprob` string macro for this or otherwise maybe also the `predict` function. We currently don't have a flag that allows you to store the intermediate log joint or log-likelihood values while sampling.

@mohamed82008 is that correct?

**Comment by mohamed82008** [comment]
Yes this is correct. The logprob macro is documented here https://turing.ml/dev/docs/using-turing/guide#querying-probabilities-from-model-or-chain.

**Comment by luiarthur** [comment]
Worked! Thanks.
